config/routes.rb
Fitzapp::Application.routes.draw do
  resources :tasks
  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :sessions, only: [:new, :create, :destroy]
  root 'tasks#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :text, :user

  def is_old?
    past = 2.weeks.ago
    past > created_at
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :tasks

  validates_presence_of :name, :password
  validates_uniqueness_of :name
  validates_length_of :name, :within => 2..20, :too_long => "must be less than 20 characters.", :too_short => "must be at least 2 characters."
  validates_length_of :password, :within => 6..15, :too_long => "must be less than 15 characters.", :too_short => "must be at least 6 characters."
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  protect_from_forgery with: :exception

  before_filter :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render "new"
  end

  def create
    @user = User.find_by_name(params[:name])
    if @user && @user.authenticate(params[:password])
      create_session
      redirect_to @user
    elsif @user.nil?
      @error = "An account with the email address #{params[:email]} not found."
      render "new"
    else
      @error = "Authentication failed."
      render "new"
    end
  end

  def destroy
    destroy_session
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    if @current_user
      @tasks = Task.where(user: @current_user)
    else
      @tasks = Task.limit(10)
      flash[:error] = "Log in to manage tasks."
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    unless is_owner?
      flash[:error] = "Not your task!"
      render "shared/error"
    end
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user = @current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:text, :completed, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    unless is_user?
      flash[:error] = "Not your account!"
      render "shared/error"
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        create_session
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= session[:current_user_id] && User.find_by_id(session[:current_user_id])
  end

  def create_session
    session[:current_user_id] = @user.id
  end

  def destroy_session
    session[:current_user_id] = nil
  end

  def is_owner?
    @task.user == @current_user
  end

  def is_user?
    @user == @current_user
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fitzapp</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
    <style>
      .content { padding-top: 80px; }
    </style>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Fitzapp</a>
          <div class="container nav-collapse">
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container content">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Menu</h3>
              <ul class="nav nav-list">
                <% if @current_user %>
                  <li class="nav-header">Welcome <%= @current_user.name %></li>
                  <li><%= link_to "All tasks", tasks_path %></li>
                  <li><%= link_to "New task", new_task_path %></li>
                  <li><%= link_to "View profile", user_path(@current_user) %></li>
                  <li><%= link_to "Edit profile", edit_user_path(@current_user) %></li>
                  <li>&nbsp;</li>
                  <li class="nav"><%= link_to "Log out", session_path(@current_user), method: :delete %></li>
                <% else %>
                  <li class="nav-header">Hello</li>
                  <li><%= link_to "Sign up", new_user_path %></li>
                  <li><%= link_to "Log in", new_session_path %></li>
                <% end %>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

    </div> <!-- /container -->

  </body>
</html>

app/views/tasks/_button.html.erb
<%= button_to task_path(object, :task => data), options do %>
  <%= content_tag('i', nil, class: button_icon) %>
  <%= button_text %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th colspan='2'>Task</th>
      <% if @current_user %>
        <th>Manage</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td>
          <%= task.text %>
        </td>
        <td>
          <% if task.completed %>
            <span class="badge badge-success"><i class="icon-ok"></i></span>
          <% end %>
          <% if task.is_old? %>
            <span class="badge badge-important"><i class="icon-exclamation-sign"></i></span>
          <% end %>
        </td>
        <% if @current_user %>
          <td>
            <% if task.completed %>
              <%= render :partial => "button" ,:locals => {
                :object => task, :data => {:completed => false},
                :options => {:method => :put, class: 'btn btn-warning btn-mini'},
                :button_icon => 'icon-remove',
                :button_text => 'Undo'
              }%>
            <% else %>
              <%= render :partial => "button" ,:locals => {
                :object => task, :data => {:completed => true},
                :options => {:method => :put, class: 'btn btn-primary btn-mini'},
                :button_icon => 'icon-ok',
                :button_text => 'Complete'
              }%>
            <% end %>
            <%= button_to edit_task_path(task), :method => :get, :class => 'btn btn-mini btn-success' do %>
              <%= content_tag('i', nil, class: 'icon-pencil') %>
              Edit
            <% end %>
            <%= render :partial => "button" ,:locals => {
                :object => task, :data => {},
                :options => {:method => :delete, class: 'btn btn-danger btn-mini'},
                :button_icon => 'icon-trash',
                :button_text => 'Delete'
            }%>
          </td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<strong>Task legend</strong>
<dl class="dl-horizontal">
  <dt><span class="badge badge-success"><i class="icon-ok"></i></span></dt>
  <dd>Completed</dd>
  <dt><span class="badge badge-important"><i class="icon-exclamation-sign"></i></span></dt>
  <dd>&gt; 2 weeks old</dd>
</dl>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @task.text %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password digest</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.name %></h1>

<p>You have <span class="label label-important"><%= @user.tasks.count %></span> tasks.</p>